{-# LANGUAGE DeriveDataTypeable #-}
-- Initially generated by TH (src-TH/Data/OneOfN.hs)
module Data.OneOfN where

import Data.Data (Data, Typeable)

data OneOf2 t1 t2
    = OneOf2 !t1 | TwoOf2 !t2
    deriving (Eq, Ord, Read, Show, Data, Typeable)
oneOf2 f1 f2 (OneOf2 x) = f1 x
oneOf2 f1 f2 (TwoOf2 x) = f2 x
data OneOf3 t1 t2 t3
    = OneOf3 !t1 | TwoOf3 !t2 | ThreeOf3 !t3
    deriving (Eq, Ord, Read, Show, Data, Typeable)
oneOf3 f1 f2 f3 (OneOf3 x) = f1 x
oneOf3 f1 f2 f3 (TwoOf3 x) = f2 x
oneOf3 f1 f2 f3 (ThreeOf3 x) = f3 x
data OneOf4 t1 t2 t3 t4
    = OneOf4 !t1 | TwoOf4 !t2 | ThreeOf4 !t3 | FourOf4 !t4
    deriving (Eq, Ord, Read, Show, Data, Typeable)
oneOf4 f1 f2 f3 f4 (OneOf4 x) = f1 x
oneOf4 f1 f2 f3 f4 (TwoOf4 x) = f2 x
oneOf4 f1 f2 f3 f4 (ThreeOf4 x) = f3 x
oneOf4 f1 f2 f3 f4 (FourOf4 x) = f4 x
data OneOf5 t1 t2 t3 t4 t5
    = OneOf5 !t1 |
      TwoOf5 !t2 |
      ThreeOf5 !t3 |
      FourOf5 !t4 |
      FiveOf5 !t5
    deriving (Eq, Ord, Read, Show, Data, Typeable)
oneOf5 f1 f2 f3 f4 f5 (OneOf5 x) = f1 x
oneOf5 f1 f2 f3 f4 f5 (TwoOf5 x) = f2 x
oneOf5 f1 f2 f3 f4 f5 (ThreeOf5 x) = f3 x
oneOf5 f1 f2 f3 f4 f5 (FourOf5 x) = f4 x
oneOf5 f1 f2 f3 f4 f5 (FiveOf5 x) = f5 x
data OneOf6 t1 t2 t3 t4 t5 t6
    = OneOf6 !t1 |
      TwoOf6 !t2 |
      ThreeOf6 !t3 |
      FourOf6 !t4 |
      FiveOf6 !t5 |
      SixOf6 !t6
    deriving (Eq, Ord, Read, Show, Data, Typeable)
oneOf6 f1 f2 f3 f4 f5 f6 (OneOf6 x) = f1 x
oneOf6 f1 f2 f3 f4 f5 f6 (TwoOf6 x) = f2 x
oneOf6 f1 f2 f3 f4 f5 f6 (ThreeOf6 x) = f3 x
oneOf6 f1 f2 f3 f4 f5 f6 (FourOf6 x) = f4 x
oneOf6 f1 f2 f3 f4 f5 f6 (FiveOf6 x) = f5 x
oneOf6 f1 f2 f3 f4 f5 f6 (SixOf6 x) = f6 x
data OneOf7 t1 t2 t3 t4 t5 t6 t7
    = OneOf7 !t1 |
      TwoOf7 !t2 |
      ThreeOf7 !t3 |
      FourOf7 !t4 |
      FiveOf7 !t5 |
      SixOf7 !t6 |
      SevenOf7 !t7
    deriving (Eq, Ord, Read, Show, Data, Typeable)
oneOf7 f1 f2 f3 f4 f5 f6 f7 (OneOf7 x) = f1 x
oneOf7 f1 f2 f3 f4 f5 f6 f7 (TwoOf7 x) = f2 x
oneOf7 f1 f2 f3 f4 f5 f6 f7 (ThreeOf7 x) = f3 x
oneOf7 f1 f2 f3 f4 f5 f6 f7 (FourOf7 x) = f4 x
oneOf7 f1 f2 f3 f4 f5 f6 f7 (FiveOf7 x) = f5 x
oneOf7 f1 f2 f3 f4 f5 f6 f7 (SixOf7 x) = f6 x
oneOf7 f1 f2 f3 f4 f5 f6 f7 (SevenOf7 x) = f7 x
data OneOf8 t1 t2 t3 t4 t5 t6 t7 t8
    = OneOf8 !t1 |
      TwoOf8 !t2 |
      ThreeOf8 !t3 |
      FourOf8 !t4 |
      FiveOf8 !t5 |
      SixOf8 !t6 |
      SevenOf8 !t7 |
      EightOf8 !t8
    deriving (Eq, Ord, Read, Show)
oneOf8 f1 f2 f3 f4 f5 f6 f7 f8 (OneOf8 x) = f1 x
oneOf8 f1 f2 f3 f4 f5 f6 f7 f8 (TwoOf8 x) = f2 x
oneOf8 f1 f2 f3 f4 f5 f6 f7 f8 (ThreeOf8 x) = f3 x
oneOf8 f1 f2 f3 f4 f5 f6 f7 f8 (FourOf8 x) = f4 x
oneOf8 f1 f2 f3 f4 f5 f6 f7 f8 (FiveOf8 x) = f5 x
oneOf8 f1 f2 f3 f4 f5 f6 f7 f8 (SixOf8 x) = f6 x
oneOf8 f1 f2 f3 f4 f5 f6 f7 f8 (SevenOf8 x) = f7 x
oneOf8 f1 f2 f3 f4 f5 f6 f7 f8 (EightOf8 x) = f8 x
data OneOf9 t1 t2 t3 t4 t5 t6 t7 t8 t9
    = OneOf9 !t1 |
      TwoOf9 !t2 |
      ThreeOf9 !t3 |
      FourOf9 !t4 |
      FiveOf9 !t5 |
      SixOf9 !t6 |
      SevenOf9 !t7 |
      EightOf9 !t8 |
      NineOf9 !t9
    deriving (Eq, Ord, Read, Show)
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (OneOf9 x) = f1 x
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (TwoOf9 x) = f2 x
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (ThreeOf9 x) = f3 x
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (FourOf9 x) = f4 x
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (FiveOf9 x) = f5 x
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (SixOf9 x) = f6 x
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (SevenOf9 x) = f7 x
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (EightOf9 x) = f8 x
oneOf9 f1 f2 f3 f4 f5 f6 f7 f8 f9 (NineOf9 x) = f9 x
data OneOf10 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10
    = OneOf10 !t1 |
      TwoOf10 !t2 |
      ThreeOf10 !t3 |
      FourOf10 !t4 |
      FiveOf10 !t5 |
      SixOf10 !t6 |
      SevenOf10 !t7 |
      EightOf10 !t8 |
      NineOf10 !t9 |
      Choice10Of10 !t10
    deriving (Eq, Ord, Read, Show)
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (OneOf10 x) = f1 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (TwoOf10 x) = f2 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (ThreeOf10 x) = f3 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (FourOf10 x) = f4 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (FiveOf10 x) = f5 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (SixOf10 x) = f6 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (SevenOf10 x) = f7 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (EightOf10 x) = f8 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (NineOf10 x) = f9 x
oneOf10 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 (Choice10Of10 x) = f10 x
data OneOf11 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11
    = OneOf11 !t1 |
      TwoOf11 !t2 |
      ThreeOf11 !t3 |
      FourOf11 !t4 |
      FiveOf11 !t5 |
      SixOf11 !t6 |
      SevenOf11 !t7 |
      EightOf11 !t8 |
      NineOf11 !t9 |
      Choice10Of11 !t10 |
      Choice11Of11 !t11
    deriving (Eq, Ord, Read, Show)
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (OneOf11 x) = f1 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (TwoOf11 x) = f2 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (ThreeOf11 x) = f3 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (FourOf11 x) = f4 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (FiveOf11 x) = f5 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (SixOf11 x) = f6 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (SevenOf11 x) = f7 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (EightOf11 x) = f8 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (NineOf11 x) = f9 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (Choice10Of11 x) = f10 x
oneOf11 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 (Choice11Of11 x) = f11 x
data OneOf12 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12
    = OneOf12 !t1 |
      TwoOf12 !t2 |
      ThreeOf12 !t3 |
      FourOf12 !t4 |
      FiveOf12 !t5 |
      SixOf12 !t6 |
      SevenOf12 !t7 |
      EightOf12 !t8 |
      NineOf12 !t9 |
      Choice10Of12 !t10 |
      Choice11Of12 !t11 |
      Choice12Of12 !t12
    deriving (Eq, Ord, Read, Show)
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (OneOf12 x) = f1 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (TwoOf12 x) = f2 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (ThreeOf12 x) = f3 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (FourOf12 x) = f4 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (FiveOf12 x) = f5 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (SixOf12 x) = f6 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (SevenOf12 x) = f7 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (EightOf12 x) = f8 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (NineOf12 x) = f9 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (Choice10Of12 x)
  = f10 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (Choice11Of12 x)
  = f11 x
oneOf12 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 (Choice12Of12 x)
  = f12 x
data OneOf13 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13
    = OneOf13 !t1 |
      TwoOf13 !t2 |
      ThreeOf13 !t3 |
      FourOf13 !t4 |
      FiveOf13 !t5 |
      SixOf13 !t6 |
      SevenOf13 !t7 |
      EightOf13 !t8 |
      NineOf13 !t9 |
      Choice10Of13 !t10 |
      Choice11Of13 !t11 |
      Choice12Of13 !t12 |
      Choice13Of13 !t13
    deriving (Eq, Ord, Read, Show)
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (OneOf13 x)
  = f1 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (TwoOf13 x)
  = f2 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (ThreeOf13 x)
  = f3 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (FourOf13 x)
  = f4 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (FiveOf13 x)
  = f5 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (SixOf13 x)
  = f6 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (SevenOf13 x)
  = f7 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (EightOf13 x)
  = f8 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (NineOf13 x)
  = f9 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (Choice10Of13 x)
  = f10 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (Choice11Of13 x)
  = f11 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (Choice12Of13 x)
  = f12 x
oneOf13 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 (Choice13Of13 x)
  = f13 x
data OneOf14 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14
    = OneOf14 !t1 |
      TwoOf14 !t2 |
      ThreeOf14 !t3 |
      FourOf14 !t4 |
      FiveOf14 !t5 |
      SixOf14 !t6 |
      SevenOf14 !t7 |
      EightOf14 !t8 |
      NineOf14 !t9 |
      Choice10Of14 !t10 |
      Choice11Of14 !t11 |
      Choice12Of14 !t12 |
      Choice13Of14 !t13 |
      Choice14Of14 !t14
    deriving (Eq, Ord, Read, Show)
oneOf14 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 (OneOf14 x)
  = f1 x
oneOf14 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 (TwoOf14 x)
  = f2 x
oneOf14
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  (ThreeOf14 x)
  = f3 x
oneOf14 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 (FourOf14 x)
  = f4 x
oneOf14 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 (FiveOf14 x)
  = f5 x
oneOf14 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 (SixOf14 x)
  = f6 x
oneOf14
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  (SevenOf14 x)
  = f7 x
oneOf14
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  (EightOf14 x)
  = f8 x
oneOf14 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 (NineOf14 x)
  = f9 x
oneOf14
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  (Choice10Of14 x)
  = f10 x
oneOf14
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  (Choice11Of14 x)
  = f11 x
oneOf14
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  (Choice12Of14 x)
  = f12 x
oneOf14
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  (Choice13Of14 x)
  = f13 x
oneOf14
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  (Choice14Of14 x)
  = f14 x
data OneOf15 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15
    = OneOf15 !t1 |
      TwoOf15 !t2 |
      ThreeOf15 !t3 |
      FourOf15 !t4 |
      FiveOf15 !t5 |
      SixOf15 !t6 |
      SevenOf15 !t7 |
      EightOf15 !t8 |
      NineOf15 !t9 |
      Choice10Of15 !t10 |
      Choice11Of15 !t11 |
      Choice12Of15 !t12 |
      Choice13Of15 !t13 |
      Choice14Of15 !t14 |
      Choice15Of15 !t15
    deriving (Eq, Ord, Read, Show)
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (OneOf15 x)
  = f1 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (TwoOf15 x)
  = f2 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (ThreeOf15 x)
  = f3 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (FourOf15 x)
  = f4 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (FiveOf15 x)
  = f5 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (SixOf15 x)
  = f6 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (SevenOf15 x)
  = f7 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (EightOf15 x)
  = f8 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (NineOf15 x)
  = f9 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (Choice10Of15 x)
  = f10 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (Choice11Of15 x)
  = f11 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (Choice12Of15 x)
  = f12 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (Choice13Of15 x)
  = f13 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (Choice14Of15 x)
  = f14 x
oneOf15
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  (Choice15Of15 x)
  = f15 x
data OneOf16 t1 t2 t3 t4 t5 t6 t7 t8 t9 t10 t11 t12 t13 t14 t15 t16
    = OneOf16 !t1 |
      TwoOf16 !t2 |
      ThreeOf16 !t3 |
      FourOf16 !t4 |
      FiveOf16 !t5 |
      SixOf16 !t6 |
      SevenOf16 !t7 |
      EightOf16 !t8 |
      NineOf16 !t9 |
      Choice10Of16 !t10 |
      Choice11Of16 !t11 |
      Choice12Of16 !t12 |
      Choice13Of16 !t13 |
      Choice14Of16 !t14 |
      Choice15Of16 !t15 |
      Choice16Of16 !t16
    deriving (Eq, Ord, Read, Show)
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (OneOf16 x)
  = f1 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (TwoOf16 x)
  = f2 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (ThreeOf16 x)
  = f3 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (FourOf16 x)
  = f4 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (FiveOf16 x)
  = f5 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (SixOf16 x)
  = f6 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (SevenOf16 x)
  = f7 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (EightOf16 x)
  = f8 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (NineOf16 x)
  = f9 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (Choice10Of16 x)
  = f10 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (Choice11Of16 x)
  = f11 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (Choice12Of16 x)
  = f12 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (Choice13Of16 x)
  = f13 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (Choice14Of16 x)
  = f14 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (Choice15Of16 x)
  = f15 x
oneOf16
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  (Choice16Of16 x)
  = f16 x
data OneOf17 t1
             t2
             t3
             t4
             t5
             t6
             t7
             t8
             t9
             t10
             t11
             t12
             t13
             t14
             t15
             t16
             t17
    = OneOf17 !t1 |
      TwoOf17 !t2 |
      ThreeOf17 !t3 |
      FourOf17 !t4 |
      FiveOf17 !t5 |
      SixOf17 !t6 |
      SevenOf17 !t7 |
      EightOf17 !t8 |
      NineOf17 !t9 |
      Choice10Of17 !t10 |
      Choice11Of17 !t11 |
      Choice12Of17 !t12 |
      Choice13Of17 !t13 |
      Choice14Of17 !t14 |
      Choice15Of17 !t15 |
      Choice16Of17 !t16 |
      Choice17Of17 !t17
    deriving (Eq, Ord, Read, Show)
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (OneOf17 x)
  = f1 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (TwoOf17 x)
  = f2 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (ThreeOf17 x)
  = f3 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (FourOf17 x)
  = f4 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (FiveOf17 x)
  = f5 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (SixOf17 x)
  = f6 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (SevenOf17 x)
  = f7 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (EightOf17 x)
  = f8 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (NineOf17 x)
  = f9 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (Choice10Of17 x)
  = f10 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (Choice11Of17 x)
  = f11 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (Choice12Of17 x)
  = f12 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (Choice13Of17 x)
  = f13 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (Choice14Of17 x)
  = f14 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (Choice15Of17 x)
  = f15 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (Choice16Of17 x)
  = f16 x
oneOf17
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  (Choice17Of17 x)
  = f17 x
data OneOf18 t1
             t2
             t3
             t4
             t5
             t6
             t7
             t8
             t9
             t10
             t11
             t12
             t13
             t14
             t15
             t16
             t17
             t18
    = OneOf18 !t1 |
      TwoOf18 !t2 |
      ThreeOf18 !t3 |
      FourOf18 !t4 |
      FiveOf18 !t5 |
      SixOf18 !t6 |
      SevenOf18 !t7 |
      EightOf18 !t8 |
      NineOf18 !t9 |
      Choice10Of18 !t10 |
      Choice11Of18 !t11 |
      Choice12Of18 !t12 |
      Choice13Of18 !t13 |
      Choice14Of18 !t14 |
      Choice15Of18 !t15 |
      Choice16Of18 !t16 |
      Choice17Of18 !t17 |
      Choice18Of18 !t18
    deriving (Eq, Ord, Read, Show)
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (OneOf18 x)
  = f1 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (TwoOf18 x)
  = f2 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (ThreeOf18 x)
  = f3 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (FourOf18 x)
  = f4 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (FiveOf18 x)
  = f5 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (SixOf18 x)
  = f6 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (SevenOf18 x)
  = f7 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (EightOf18 x)
  = f8 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (NineOf18 x)
  = f9 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice10Of18 x)
  = f10 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice11Of18 x)
  = f11 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice12Of18 x)
  = f12 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice13Of18 x)
  = f13 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice14Of18 x)
  = f14 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice15Of18 x)
  = f15 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice16Of18 x)
  = f16 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice17Of18 x)
  = f17 x
oneOf18
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  (Choice18Of18 x)
  = f18 x
data OneOf19 t1
             t2
             t3
             t4
             t5
             t6
             t7
             t8
             t9
             t10
             t11
             t12
             t13
             t14
             t15
             t16
             t17
             t18
             t19
    = OneOf19 !t1 |
      TwoOf19 !t2 |
      ThreeOf19 !t3 |
      FourOf19 !t4 |
      FiveOf19 !t5 |
      SixOf19 !t6 |
      SevenOf19 !t7 |
      EightOf19 !t8 |
      NineOf19 !t9 |
      Choice10Of19 !t10 |
      Choice11Of19 !t11 |
      Choice12Of19 !t12 |
      Choice13Of19 !t13 |
      Choice14Of19 !t14 |
      Choice15Of19 !t15 |
      Choice16Of19 !t16 |
      Choice17Of19 !t17 |
      Choice18Of19 !t18 |
      Choice19Of19 !t19
    deriving (Eq, Ord, Read, Show)
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (OneOf19 x)
  = f1 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (TwoOf19 x)
  = f2 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (ThreeOf19 x)
  = f3 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (FourOf19 x)
  = f4 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (FiveOf19 x)
  = f5 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (SixOf19 x)
  = f6 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (SevenOf19 x)
  = f7 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (EightOf19 x)
  = f8 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (NineOf19 x)
  = f9 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice10Of19 x)
  = f10 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice11Of19 x)
  = f11 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice12Of19 x)
  = f12 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice13Of19 x)
  = f13 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice14Of19 x)
  = f14 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice15Of19 x)
  = f15 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice16Of19 x)
  = f16 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice17Of19 x)
  = f17 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice18Of19 x)
  = f18 x
oneOf19
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  (Choice19Of19 x)
  = f19 x
data OneOf20 t1
             t2
             t3
             t4
             t5
             t6
             t7
             t8
             t9
             t10
             t11
             t12
             t13
             t14
             t15
             t16
             t17
             t18
             t19
             t20
    = OneOf20 !t1 |
      TwoOf20 !t2 |
      ThreeOf20 !t3 |
      FourOf20 !t4 |
      FiveOf20 !t5 |
      SixOf20 !t6 |
      SevenOf20 !t7 |
      EightOf20 !t8 |
      NineOf20 !t9 |
      Choice10Of20 !t10 |
      Choice11Of20 !t11 |
      Choice12Of20 !t12 |
      Choice13Of20 !t13 |
      Choice14Of20 !t14 |
      Choice15Of20 !t15 |
      Choice16Of20 !t16 |
      Choice17Of20 !t17 |
      Choice18Of20 !t18 |
      Choice19Of20 !t19 |
      Choice20Of20 !t20
    deriving (Eq, Ord, Read, Show)
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (OneOf20 x)
  = f1 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (TwoOf20 x)
  = f2 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (ThreeOf20 x)
  = f3 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (FourOf20 x)
  = f4 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (FiveOf20 x)
  = f5 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (SixOf20 x)
  = f6 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (SevenOf20 x)
  = f7 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (EightOf20 x)
  = f8 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (NineOf20 x)
  = f9 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice10Of20 x)
  = f10 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice11Of20 x)
  = f11 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice12Of20 x)
  = f12 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice13Of20 x)
  = f13 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice14Of20 x)
  = f14 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice15Of20 x)
  = f15 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice16Of20 x)
  = f16 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice17Of20 x)
  = f17 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice18Of20 x)
  = f18 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice19Of20 x)
  = f19 x
oneOf20
  f1
  f2
  f3
  f4
  f5
  f6
  f7
  f8
  f9
  f10
  f11
  f12
  f13
  f14
  f15
  f16
  f17
  f18
  f19
  f20
  (Choice20Of20 x)
  = f20 x
